[package]
name = "memory_cache"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = { version = "3", features = ["derive", "env"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"